/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_ryan_com_ndkdemo_jni_MathKit */

#ifndef _Included_android_ryan_com_ndkdemo_jni_MathKit
#define _Included_android_ryan_com_ndkdemo_jni_MathKit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_ryan_com_ndkdemo_jni_MathKit
 * Method:    square
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_android_ryan_com_ndkdemo_jni_MathKit_square
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
