package com.ryan.java.reflect;

/**
 * A synthetic class (or method) is a class (or method) that is generated by the
 * compiler. For example, if you create an anonymous inner class in your code,
 * like this:
 *
 */
public class SyntheticClassSample {

	public class MyClass {
		public void someMethod() {
	        Runnable r = new Runnable() {
	            @Override
	            public void run() {
	                System.out.println("Hello World!");
	            }
	        };
	        r.run();
	    }
	}

	public static void main(String[] args) throws Exception {
		MyClass myClass = (new SyntheticClassSample()).new MyClass();
		myClass.someMethod();
		boolean synthetic = Class.forName("MyClass$1").isSynthetic();
		System.out.println("Synthetic? " + synthetic);
	}

}
